//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DowntownDeliProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empworktime
    {
        public int Work_Time_ID { get; set; }
        public int Emp_ID { get; set; }
        public int Job_ID { get; set; }
        public System.DateTime Clock_In { get; set; }
        public System.DateTime Clock_Out { get; set; }
        public System.DateTime Work_Date { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Job Job { get; set; }
    }
}
