//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DowntownDeliProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Order
    {
        public long Inv_Ord_ID { get; set; }
        public Nullable<long> Item_ID { get; set; }
        public Nullable<long> Vendor_ID { get; set; }
        public int Quantity { get; set; }
        public decimal Total_Cost { get; set; }
        public System.DateTime Delivery_Date { get; set; }
        public System.DateTime Purchase_Date { get; set; }
    
        public virtual Vendor Vendor { get; set; }
        public virtual Inventory Inventory { get; set; }
    }
}
