//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DowntownDeliProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Product_Order = new HashSet<Product_Order>();
        }
    
        public long Order_ID { get; set; }
        public Nullable<long> Customer_ID { get; set; }
        public Nullable<long> Promo_ID { get; set; }
        public decimal Price { get; set; }
        public System.DateTime Ord_Date { get; set; }
        public int Points { get; set; }
        public Nullable<bool> Complete { get; set; }
        public string Order_Type { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Order> Product_Order { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
