//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DowntownDeliProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Order
    {
        public System.Guid Product_Order_ID { get; set; }
        public System.Guid Product_ID { get; set; }
        public System.Guid Order_ID { get; set; }
        public System.Guid Promo_ID { get; set; }
        public System.Guid Customer_ID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
